config/routes.rb
BuildingManager::Application.routes.draw do
  resources :tenants

  resources :buildings

  resources :owners

  root 'pages#home'

end

app/models/building.rb
class Building < ActiveRecord::Base
VALID_STATES = [
  "AL",
  "AK",
  "AZ",
  "AR",
  "CA",
  "CO",
  "CT",
  "DE",
  "FL",
  "GA",
  "HI",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "OH",
  "OK",
  "OR",
  "PA",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VT",
  "VA",
  "WA",
  "WV",
  "WI",
  "WY"

]
  validates_presence_of :street_address
  validates_presence_of :city

  validates_inclusion_of :state,
    in: VALID_STATES

  validates_format_of :postal_code,
    :with => /\A\d{5}\z/,
    :message => "should be 12345"

  validates_length_of :postal_code,
    :is => 5

  belongs_to :owner,
    inverse_of: :buildings

  has_many :tenants,
    inverse_of: :building

end

app/models/owner.rb
class Owner < ActiveRecord::Base

  validates_presence_of :first_name
  validates_presence_of :last_name

  validates_format_of :email,
    with: /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}/i,
    :message => "should be a valid email address"

  has_many :buildings,
    inverse_of: :owner,
    dependent: :nullify

  has_many :tenants,
    through: :buildings,
    inverse_of: :owner

  def full_name
    '#{first_name} #{last_name}'
  end

end

app/models/tenant.rb
class Tenant < ActiveRecord::Base

  validates_presence_of :first_name
  validates_presence_of :last_name

  validates_format_of :email,
    with: /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}/i,
    :message => "should be a valid email address"

  validates_numericality_of :building_id,
    only_integers: true,
    greater_than_or_equal_to: 1

  belongs_to :building,
    inverse_of: :tenants

  has_one :owner,
    through: :buildings,
    inverse_of: :tenants

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  def new
    @building = Building.new
  end

  def index
    @buildings = Building.all
  end

  def create
    @building = Building.new(building_params)
    if @building.save
      flash[:notice] = "Building was successfully recorded"
      redirect_to @building
    else
      render :new
    end
  end

  def show
    @building = Building.find(params[:id])
  end

  protected
  def building_params
    params.require(:building).permit(:street_address, :city, :state, :postal_code, :description, :owner_id)
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.new(owner_params)
    if @owner.save
      flash[:notice] = "Owner was successfully recorded"
      redirect_to @owner
    else
      render :new
    end
  end

  def index
    @owners = Owner.all
    @owners.order('last_name').order('first_name')
  end

  def destroy
    @owner = Owner.find(params[:id])
    @owner.destroy
    redirect_to owners_path, notice: "Owner was successfully deleted"
  end

  def show
    @owner = Owner.find(params[:id])
  end

  protected

  def owner_params
    params.require(:owner).permit(:last_name, :first_name, :company, :email, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController

  def new
    @tenant = Tenant.new
  end

  def create
    @tenant = Tenant.new(tenant_params)
    if @tenant.save
      flash[:notice] = "Tenant was successfully recorded"
      redirect_to @tenant
    else
      render :new
    end
  end

  def index
    @tenants = Tenant.order('last_name')
  end

  def destroy
    @tenant = Tenant.find(params[:id])
    @tenant.destroy
    flash[:notice] = "Tenant was successfully deleted"
    redirect_to tenants_path
  end

  def index
    @tenants = Tenant.order('last_name')
  end

  def show
    @tenant = Tenant.find(params[:id])
  end


  protected
  def tenant_params
    params.require(:tenant).permit(:last_name, :first_name, :building_id, :email, :description)
  end

end

app/views/buildings/index.html.erb
<h1>List of Buildings</h1>

    <% @buildings.each do |building| %>
     <div>
      <ul class='main'>
        <li>Building Address:</li>
        <li><%= building.street_address %></li>
        <li><%= building.city + ' ' + building.state  %></li>
        <% owner = Owner.find(building.owner_id) %>
        <li>Building Owner: <%= owner.first_name + ' ' + owner.last_name %></li>
        <li><%= button_to 'Delete', building, method: :delete, data: { confirm: 'Are you sure you want to delete this building?' } %></li>
      </ul>
      <hr />
    </div>
    <% end %>
<br>
<h4><%= link_to 'Add a new building', new_building_path %></h4>

app/views/buildings/new.html.erb
  <%= form_for @building do |f| %>

    <% if @building.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@building.errors.count, "error") %> prohibited this event from being saved:</h2>

        <ul>
          <% @building.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field form-group">
      <%= f.label :street_address %><br />
      <%= f.text_field :street_address %>
    </div>

    <div class="field form-group">
      <%= f.label :city %><br />
      <%= f.text_field :city %>
    </div>

    <div class="field form-group">
      <%= f.label :owner_id %><br />
      <%= f.collection_select :owner_id, Owner.all, :id, :first_name, include_blank: true %>
    </div>

    <div class="actions">
      <%= f.submit 'Record', class: "submit btn btn-default" %>
    </div>

  <% end %>

app/views/buildings/show.html.erb
<h1>New Building</h1>
  <div>
    <ul class='main'>
      <li><%= @building.street_address %></li>
      <li><%= @building.city + ' ' + @building.state + ' ' + @building.postal_code %></li>
      <li><%= button_to 'Delete', @building, method: :delete, data: { confirm: 'Are you sure you want to delete this building?' } %></li>
    </ul>
  </div>
<br>

  <h4><%= link_to 'Add a new building', new_building_path %></h4>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Building Manager</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="col-md-10 col-md-offset-1">
    <h1><%= link_to 'Building Management System', root_path %></h1>
  </div>

  <div class="col-md-10 col-md-offset-1">
    <ul class="nav nav-tabs">
      <li><%= link_to 'Owners', owners_path %></li>
      <li><%= link_to 'Buildings', buildings_path %></li>
      <li><%= link_to 'Tenants', tenants_path %></li>
    </ul>
  </div>

  <div class="col-md-10 col-md-offset-1">
  <%= notice %>

  <%= yield %>
  </div>
</body>
</html>

app/views/owners/index.html.erb
<h1>Listing Owners</h1>

  <% @owners.each do |owner| %>
  <div>
    <ul class='main'>
      <li><%= owner.first_name  + ' ' + owner.last_name %></li>
      <li><%= owner.email %></li>
      <li>Company: <%= owner.company_name %></li>
      <li><%= button_to 'Delete', owner, method: :delete, data: { confirm: 'Are you sure you want to delete this owner?' } %></li>
    </ul>
  </div>
    <br />
  <% end %>

<br />

<h4><%= link_to 'Add a new owner', new_owner_path %></h4>

app/views/owners/new.html.erb
  <%= form_for @owner do |f| %>

    <% if @owner.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this event from being saved:</h2>

        <ul>
          <% @owner.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field form-group">
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name %>
    </div>

    <div class="field form-group">
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name %>
    </div>

    <div class="field form-group">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>

    <div class="field form-group">
      <%= f.label :company_name %><br />
      <%= f.text_field :company_name %>
    </div>

    <div class="actions">
      <%= f.submit 'Record', method: "post", class: "submit btn btn-default" %>
    </div>

  <% end %>

app/views/owners/show.html.erb
<h1>New Owner</h1>
  <div>
    <ul class='main'>
      <li><%= @owner.first_name + ' ' + @owner.last_name %></li>
      <li><%= @owner.company_name %></li>
      <li><%= button_to 'Delete', @owner, method: :delete, data: { confirm: 'Are you sure you want to delete this owner?' } %></li>
    </ul>
  </div>
<br>

<h4><%= link_to 'Add a new owner', new_owner_path %></h4>

app/views/pages/home.html.erb
<div class="jumbotron">
  <div class="container">
    <h2>New Registrations</h2>
    <h3><%= link_to 'Owners', new_owner_path %></h3>
    <h3><%= link_to 'Buildings', new_building_path %></h3>
    <h3><%= link_to 'Tenants', new_tenant_path %></h3>
  </div>
</div>

app/views/tenants/index.html.erb
<h1>List of tenants</h1>
<div>
  <% @tenants.each do |tenant| %>
    <ul class=" main tenant_<%= tenant.id %>">
      <li><%= tenant.first_name + ' ' + tenant.last_name %></li>
      <li><%= tenant.email %></li>
      <li>Building: <%= tenant.building.street_address + ' ' + tenant.building.city %></li>
      <li>Building owner: <%= tenant.building.owner.first_name + ' ' + tenant.building.owner.last_name %></li>
      <li><%= button_to 'Delete', tenant, method: :delete, data: { confirm: 'Are you sure you want to delete this tenant?' } %></li>
    </ul>
  <% end %>
</div>
  <br>

<h4><%= link_to 'Add a new tenant', new_tenant_path %></h4>

app/views/tenants/new.html.erb
  <%= form_for @tenant do |f| %>

    <% if @tenant.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@tenant.errors.count, "error") %> prohibited this event from being saved:</h2>

        <ul>
          <% @tenant.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field form-group">
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name %>
    </div>

    <div class="field form-group">
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name %>
    </div>

    <div class="field form-group">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>

    <div class="field form-group">
      <%= f.label :building_id %><br />
      <%= f.collection_select :building_id, Building.all, :id, :street_address, include_blank: true %>
    </div>

    <div class="actions">
      <%= f.submit 'Record', method: "post", class: "btn btn-default" %>
    </div>

  <% end %>

app/views/tenants/show.html.erb
<h1>New Tenant</h1>
<div>
  <ul class='main'>
    <li><%= @tenant.first_name + ' ' + @tenant.last_name %></li>
    <li><%= @tenant.email %></li>
    <li><%= @tenant.building.street_address %></li>
    <li><%= @tenant.building.city %></li>
    <li><%= button_to 'Delete', @tenant, method: :delete, data: { confirm: 'Are you sure you want to delete this tenant?' } %></li>
  </ul>
</div>
<br>

<h4><%= link_to 'Add a new tenant', new_tenant_path %></h4>